// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZtuChJCLXuZiuJB7okNR4W80pQuMXEO8',
    appId: '1:112195151056:web:0d10fca5488957e4e8ead5',
    messagingSenderId: '112195151056',
    projectId: 'car-rental-app-d5750',
    authDomain: 'car-rental-app-d5750.firebaseapp.com',
    storageBucket: 'car-rental-app-d5750.firebasestorage.app',
    measurementId: 'G-0023G04632',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzVzZ8pPfoW85wD7sdI0BzyUP0115k1ZU',
    appId: '1:112195151056:android:a08c17af981a3350e8ead5',
    messagingSenderId: '112195151056',
    projectId: 'car-rental-app-d5750',
    storageBucket: 'car-rental-app-d5750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSSfLfSRK_YbvBFXv84hNBuTUtkprBY-M',
    appId: '1:112195151056:ios:8dbcdcf93a52afd7e8ead5',
    messagingSenderId: '112195151056',
    projectId: 'car-rental-app-d5750',
    storageBucket: 'car-rental-app-d5750.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSSfLfSRK_YbvBFXv84hNBuTUtkprBY-M',
    appId: '1:112195151056:ios:8dbcdcf93a52afd7e8ead5',
    messagingSenderId: '112195151056',
    projectId: 'car-rental-app-d5750',
    storageBucket: 'car-rental-app-d5750.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZtuChJCLXuZiuJB7okNR4W80pQuMXEO8',
    appId: '1:112195151056:web:8309612e27665f8fe8ead5',
    messagingSenderId: '112195151056',
    projectId: 'car-rental-app-d5750',
    authDomain: 'car-rental-app-d5750.firebaseapp.com',
    storageBucket: 'car-rental-app-d5750.firebasestorage.app',
    measurementId: 'G-ZLHTBED6YP',
  );
}
